project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "Andrew Villeneuve"
  site-url: https://villesci.github.io
  twitter-card: true
  favicon: 'images/bahamafull.jpg'
  google-analytics: 
    tracking-id: "G-S82TX4CM9T"
    anonymize-ip: true
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: posts.qmd
        text: Blog
    right:
      -icon: github
      href: "https://github.com/villesci"
      -icon: twitter
      href: "https://twitter.com/villeneuvesci"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    

editor: visual


