project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "Andrew Villeneuve"
  site-url: https://villesci.github.io
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      background: success
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual


