---
title: "Publications"
format:
  html:
    page-layout: full
    title-block-banner: "images/bahama.jpg"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: body
---

Sasaki, M, JM Barley, S. Gignoux-Wolfsohn, CG Hays, MW Kelly, AB Putnam, SN Sheth, **AR Villeneuve,** BS Cheng. 2022. Greater evolutionary divergence of thermal limits within marine than terrestrial species. *Nature Climate Change* 12: 1175-1180 *PDF on request* \| [Link](https://www.nature.com/articles/s41558-022-01534-y)\
**\
**Barley, JM, BS Cheng, M Sasaki, S Gignoux-Wolfsohn, CG Hays, AB Putnam, S Sheth, **AR Villeneuve**, MW Kelly. 2021. Limited plasticity in thermally tolerant populations: evidence for a trade-off. Proceedings of the Royal Society B 288(1958): 20210765. *PDF on request \|* [Link](https://pubmed.ncbi.nlm.nih.gov/34493077/)\
\
**​Villeneuve, AR**, LM Komoroske, BS Cheng. 2021. Environment and phenology shape local adaptation in thermal performance.   *Proceedings of the Royal Society B* 288(1955): 20210741. [***​***]{.underline}***PDF On request*** \| [[**Code and Data**]{.underline}](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1c59zw3vv) \| [[**Supplement**]{.underline}](https://rs.figshare.com/articles/journal_contribution/Supplementary_Materials_from_Environment_and_phenology_shape_local_adaptation_in_thermal_performance/14992747) [\|]{.underline} [[**Link \|**]{.underline}](https://royalsocietypublishing.org/doi/abs/10.1098/rspb.2021.0741) [[**Corrigendum**]{.underline}](https://royalsocietypublishing.org/doi/10.1098/rspb.2021.2554)\
\
**Villeneuve, AR**, LM Komoroske, BS Cheng. 2021. Diminished warming tolerance and plasticity in low latitude populations of a marine gastropod. *Conservation Physiology* 9(1): coab039. [**Full Text**](https://villesci.weebly.com/uploads/1/2/3/6/123660066/villeneuve_2021_conphys.pdf) \| [[**Code and Data**]{.underline}](https://zenodo.org/record/4644201#.YQF3845Kg2w) [\| [**Supplement**](https://villesci.weebly.com/uploads/1/2/3/6/123660066/villeneuve_lt50_ms_supplementary_4_15_coab039.docx)\| [**Link**](https://academic.oup.com/conphys/article/9/1/coab039/6297054)]{.underline}\
\
**Villeneuve, AR**, I Thornhill, J Eales. 2019*.* Upstream migration rate of an amphidromous gastropod dependent on altitude and distance from ocean, with observations on shell erosion. *Aquatic Ecology* 53(2): 205-215. [**Full text**](https://villesci.weebly.com/uploads/1/2/3/6/123660066/villeneuve2019_article_upstreammigrationandaltitudina.pdf) **\|[ Link](https://link.springer.com/article/10.1007/s10452-019-09683-7)**\
[**​**](https://villesci.weebly.com/uploads/1/2/3/6/123660066/villeneuve2019_article_upstreammigrationandaltitudina.pdf)\
Wheelwright, NT, LU Taylor, BM West, ER Voss, SY Berzins, **AR Villeneuve**, HR LeBlanc, VB Leos, SJ Mayne, SA McCarthy, SJ Nagar, JS Watling. 2017. Pupation site selection and enemy avoidance in the Introduced Pine Sawfly (*Diprion similis*).*Winter Ecology: Insights from Biology and History*, special issue of *The Northeastern Naturalist* 24(7):B19-B31. [[**Full text**]{.underline}](https://villesci.weebly.com/uploads/1/2/3/6/123660066/wheelwrightelalnenat17__2_.pdf) [\| [**Link**](https://bioone.org/journals/northeastern-naturalist/volume-24/issue-sp7/045.024.s705/Pupation-Site-Selection-and-Enemy-Avoidance-in-the-Introduced-Pine/10.1656/045.024.s705.full)]{.underline}\
 \
**Villeneuve, AR**. 2017. Habitat selection and population density of the world's smallest chameleon *Brookesia micra* on Nosy Hara, Madagascar. *Herpetological Conservation and Biology* 12(2):334-341.  [[**Full text**]{.underline}](https://villesci.weebly.com/uploads/1/2/3/6/123660066/villeneuve2017brookesiafinal.pdf)
